name: PR Changes Requested

on:
  pull_request_review:
    types:
      - submitted
  # push:
  #   branches:
  #     - master

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  notify_webhook:
    runs-on: ubuntu-latest
    environment: automation
    env: 
        WEBHOOK_TEST: ${{ secrets.WEBHOOK_TEST }}
    steps:
      - name: Check if changes were requested 
        # if: github.event.review.state == 'changes_requested'
        run: |
          curl -X POST "${WEBHOOK_TEST}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions" \
            -d '{
              "repository": "${{ github.repository }}",
              "action": "${{ github.event.action }}",
              "pull_request": "${{ github.event.pull_request.html_url }}",
              "review": "${{ github.event.review.html_url }}",
              "review_payload": "${{ github.event.review }}",
              "sender": "${{ github.actor }}"
            }'
