name: PR Activity Tracker (All Updates)

on:
  pull_request:
  pull_request_review:
  issue_comment:

jobs:
  notify_webhook:
    runs-on: ubuntu-latest
    environment: automation
    env: 
      WEBHOOK_TEST: ${{ secrets.WEBHOOK_TEST }}
    steps:
      - name: Send Webhook Notification
        run: |
          curl -X POST "${WEBHOOK_TEST}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions" \
            -d @- <<EOF
{
  "repository": "${{ github.repository }}",
  "action": "${{ github.event.action }}",
  "pull_request": ${{ toJson(github.event.pull_request) }},
  "review": "${{ github.event.review.html_url }}",
  "review_state": "${{ github.event.review.state }}",
  "comment": "${{ github.event.comment.body }}",
  "sender": "${{ github.actor }}"
}
EOF
